project:
  type: website
  output-dir: docs

website:
  title: "DD2"
  page-navigation: true
  page-footer: "SKNC" 
  #navbar:
  #  left:
  #    - href: index.qmd
  #      text: Home
  #    - about.qmd
  #    - data sources.qmd
  sidebar:
    style: "docked"
    search: true
    contents:
  #        - index.qmd #index er inkluderet i "home" men jeg har fjernet den fra sidebar
      #- section: "Data sources"
      #  contents:
      - data sources.qmd 
      
      - text: "---"
        
      - section: "DD2 core data "
        contents: 
        - dd2_questionnaire.qmd
        - dd2_biobank.qmd
      - section: "Additional DD2 data"
        #contents: 
        
      - section: "External DD2 data"
        #contents: 
        
      - section: "Registry data"
        #contents: 
        
      - text: "---"
        
      - section: "How to work"
        contents: 
        - working.qmd
        
format:
  html:
    #theme: cosmo
    theme: flatly
    css: styles.css
    toc: true



