project:
  type: website
  output-dir: docs

website:
  title: "DD2"
  page-navigation: true
  page-footer: "SKNC"  
  #navbar:
  #  left:
  #    - href: index.qmd
  #      text: Home
  #    - about.qmd
  #    - data sources.qmd
  sidebar:
    style: "docked"
    search: true
    contents:
  #        - index.qmd #index er inkluderet i "home" men jeg har fjernet den fra sidebar
      #- section: "Data sources"
      #  contents:
      - sites/data sources.qmd 
      
      - text: "---"
        
      - section: "DD2 core data "
        contents: 
        - sites/data sources/dd2_questionnaire.qmd
        - sites/data sources/dd2_biobank.qmd
        
      - section: "Additional DD2 data"
        contents: 
        - sites/data sources/idnc.qmd
        - sites/data sources/foedsel.qmd

      - section: "External DD2 data"
        contents: 
        - sites/data sources/ddda.qmd
        - sites/data sources/ddid.qmd
        - sites/data sources/diabase.qmd
        - sites/data sources/fodstatus.qmd
        
         
      - section: "Registry data"
        contents: 
        - sites/registry/SDS.qmd
        - sites/registry/DST.qmd
        
      - text: "---"
        
      - section: "How to work"
        contents: 
        - sites/working.qmd
        
format:
  html:
    #theme: cosmo
    theme: flatly
    css: styles.css
    toc: true



