---
title: "The Danish Center for Strategic Research in Type 2 Diabetes"
author:
  - name: "Sia Kromann Nicolaisen"
    email: "sknc@clin.au.dk"
    orcid: "0000-0002-6106-1945"
    url: "https://pure.au.dk/portal/en/persons/sknc%40clin.au.dk"
date: "`r format(Sys.Date(), '%Y-%m-%d')`"
engine: knitr
---


::: callout-important
This website is currently under development. 
:::

This website includes details about **The Danish Center for Strategic Research in Type 2 Diabetes** (The **DD2** Study). The intention of this website is to document the data sources used for research and to support the day-to-day work with DD2. It is mainly aimed at employees of the DCE, Aarhus University and Aarhus University Hospital, as it describes the setup used at DCE. Other institutions can also access DD2 data but their setup might differ.

To learn more about DD2, please visit the official DD2 website: <https://dd2.dk/>{target="_blank"}


Please see @Nielsen_ClinEpi_2012 for information about the initial DD2 enrollment process and the 2018 and 2024 cohort papers (Christensen et al. (2018) and Kristensen et al. (2024)) for information about enrollment, data sources, and baseline characteristics. An extensive list of [scientific publications](https://dd2.dk/nyheder/categories/videnskabelige-publikationer){target="_blank"} based on data from DD2 is available on the official website.
