---
title: "New biobank structure"
---
{{< downloadthis ../../files/variable_documentation/DD2_questionnaire.csv dname="DD2_questionnaire" icon="file-earmark-text" label="Variable documentation" type="button" class="btn btn-light">}}

::: callout-info
Indholdet og strukturen på det biobankdata afhænger af hvilke variable der er tilgængelige fra biobanken (vejle)
:::



# Ny struktur - data delt i to (måske tre)

DENNE SIDE SKAL BESKRIVE

-   DD2 BIOBANK: infodata om prøverne og kvaliteten af data (IKKE resultater)

    -   cpr/projectid (link mellem cpr og projectid)

    -   urinprøve, ja/nej

    -   blodprøve, ja/nej

    -   faste ja/nej

    -   vejledato

    -   nye data fra biobanken/vejle: antal prøver, glas, osv.

-   Biomarker: resultater fra de enkelte analyser (long format)

    -   projectid

    -   biomarker (e.g. c-pep, glucose, il6, ...)

    -   results (resultatet af analysen)

    -   unit

    -   study (hvorfor er målingen lavet?)

    -   date (f.eks. ved c-pep er der forskel på om analysen er lavet på en ny eller gammel prøve, så det kan være relevant at kende datoen for analysen så man kan sammenligne den med datoen for blodprøven).

Det kan evt. være relevant med et meta-data med henvisning til de enkelte studier.

Ideelt set vil der for enhver biomarkør være en beskrivelse af markøren/data/pitfalls/beslutninger/overvejelser etc. Et slags opslagsværk, så man har samlet information om hver markør (e.g. c-pep så man ved hvilke beslutninger der er taget). 
