---
title: "Danish Diabetes Database for Adults (DDDA)"
subtitle: "Secondary data from non-centralized data source"
---

Go to [Data documentation](ddda.qmd#data-documentation)

DDDA (also known as DVDD or NIP Diabetes) is a no longer active database from RKKP. It was closed by 30 June 2022. It has now been replaced by DDiD, which has been active since 01 July 2022. Currently, DDiD is mainly based on registry data, however, as additional data are still being recorded in the clinic, it is worth checking the database in the future, as other relevant variables might be included (e.g. smoking, blood pressure, BMI, etc.). 
<!-- https://www.sundk.dk/kliniske-kvalitetsdatabaser/dansk-diabetes-database-ddid/ -->


Extracts from the [online](https://www.rkkp-dokumentation.dk/Public/Databases.aspx?db=43&db2=1000000549){target="_blank"} DDDA documentation (downloaded 07 September 2023) about the population and variables can be downloaded here: {{< downloadthis ../../files/DDDA/RKKP_Dokumentation_DDDA_variable.pdf dname="RKKP_Dokumentation_DDDA_variable" icon="file-earmark-pdf" label="Variables" type="button" class="btn btn-link">}} {{< downloadthis ../../files/DDDA/RKKP_Dokumentation_DDDA_population.pdf dname="RKKP_Dokumentation_DDDA_population" icon="file-earmark-pdf" label="Population" type="button" class="btn btn-link">}}

And additional documents: {{< downloadthis ../../files/DDDA/dvdd_datadefinitioner_mar021.pdf dname="dvdd_datadefinitioner_mar021" icon="file-earmark-pdf" label="Datadefinitioner" type="button" class="btn btn-link">}} {{< downloadthis ../../files/DDDA/dvdd_registreringsskema_1marts2017_endelig.pdf dname="dvdd_registreringsskema_1marts2017_endelig" icon="file-earmark-pdf" label="Registreringsskema" type="button" class="btn btn-link">}} {{< downloadthis ../../files/DDDA/2023-04-24_Variabeloversigt_DVDD.pdf dname="2023-04-24_Variabeloversigt_DVDD" icon="file-earmark-pdf" label="Variabeloversigt" type="button" class="btn btn-link">}} {{< downloadthis ../../files/DDDA/NIP_sporgeskema.pdf dname="NIP_sporgeskema" icon="file-earmark-pdf" label="Questionnaire" type="button" class="btn btn-link">}}

See also @Jorgensen_ClinEpi_2016 for further information about the database.

# Data

At DCE, data is available from DDDA in the period from May 2005 to January 2022 based on the N=10,241 individuals enrolled in DD2 per January 2022. As the database is now closed, this is the final data set and it will not be updated.

The records in DDDA are uniquely defined based on the CPR-number and the variable `status_dato`, which is "den dato, hvor der årligt, i relation til databasen, gøres status over hvornår personer senest har fået foretaget forskellige relevante undersøgelser" (see [website](https://www.db-dokumentation-sundk.dk/Public/PopulationsSpecifikation21.aspx?db2=1000000549){target="_blank"}). The `status_dato` is not necessarily the date of the examination itself, and many of the variables have an associated date variable different from `status_dato` (e.g., `hba1c_dato` or `blodtryk_dato`). The dates listed for each of the examinations might be long after (or before) enrollment in DD2, and for each scientific study question, it is important to consider in which time period data can be considered valid. An example could be to only include measurements in the period from 5 years prior to enrollment in DD2 to 6 months after enrollment and then among these, include the one closest to the enrollment date as a "baseline" value. When using data from DDDA, it is also important to keep in mind the missing data. Data may be missing either because it was not reported or because the individual is simply not registered in DDDA. In the latest version of the DDDA data, around 80% (N=8,512) of the individuals in DD2 had at least one record in DDDA. Thus, when reporting data from DDDA, e.g., in a baseline table, remember to consider what "100%" should represent, as the interpretation of the result varies; is it x% of the entire study population or x% of the study population also registered in DDDA. Individuals registered in DDDA fulfill the criteria for this database (see population documentation above) which might induce some selection bias. Individuals in DDDA might not be as newly diagnosed as individuals in DD2.


------------------------------------------------------------------------

# Data documentation

## DDDA.sas7bdat

{{< downloadthis ../../files/variable_documentation/DDDA.xlsx dname="DDDA" icon="file-earmark-text" label="Variable documentation" type="button" class="btn btn-light">}}

| Format (var x obs) | Id variables | Unique key | Important dates |
|-----------------|---------------------|-----------------|-----------------|
| Wide (75 x 30,806) | CPR | CPR\*status_dato | status_dato, specific date variables |

N=8,512 distinct individuals contribute DDDA data. A record is unique based on CPR and `status_dato`, however, for many of the variables, it is worth also considering the corresponding date variable. There is a median of 3 (IQR 2-5) records per individual, 85% had at least one record prior to enrollment in DD2, and there was a median of -56 days (IQR -413-294) from the enrollment date to the nearest `status_dato` (negative value meaning that `status_dato` was before enrollment in DD2). 


| Row | CPR | status_dato | Var | Var_dato | ... |
|----|----|----|----|----|----|
| 1 | CPR1 | status_dato1.1 | num. | Var_dato1.1 | ... |
| 2 | CPR1 | status_dato1.2 | num. | Var_dato1.2 | ... |
| 3 | CPR1 | status_dato1.3 | num. | Var_dato1.2 | ... |
| ... | ... | ... | ... | ... | ... |
| 10 | CPR1 | status_dato1.10 | (missing, no record) | (missing, no record) | ... |
| 11 | CPR2 | status_dato2.1 | num. | Var_dato2.1 | ... |
| 12 | CPR2 | status_dato2.2 | num. | Var_dato2.2 | ... |
| ... | ... | ... | ... | ... | ... |
| 30,806 | CPR10219 | (missing, not in DDDA) | (missing, not in DDDA) | (missing, not in DDDA) | ... |

: Illustration of the overall data structure in DDDA.sas7bdat. The dataset is in wide format (75 variables × 30,806 rows), with CPR\*status_dato as the unique key. The data from DDDA is merged with the DD2 population, and therefore include N=10,219 distinct CPR numbers, however, only N=8,512 contribute DDDA data. 

### Variables from previous versions

In the latest DDDA data, some variables from the database were not included. The selected approach was to include these variables from previous data versions, even though they will be missing for some newly added individuals.

-   From the 2021 data: `shared_care` and `Plasmakreatinin_operator`

-   From the 2018 data (also missing in the 2021 delivery): `diag_dato`, `HbA1c_kode`, `HDLcholesterol`, and `HDLcholesterol_undersoegelse_kod`. These variables are included with a "\_2018" postfix.
