---
title: "SDS"
subtitle: "Secondary data from centralized routine registry data available on remote research server"
---

## Sundhedsdatastyrelsen (SDS)/The Danish Health Data Authority

Sundhedsdatastyrelsen - FSEID-00006014.

Download the "udtræksbeskrivelse" here:\
Dataspecifikation {{< downloadthis documents/2023-02-15-Bilag_B.docx dname="Bilag_B" icon="file-earmark-text" label="Bilag B" type="button" class="btn btn-link">}}\
Dataoversigt {{< downloadthis documents/2023-02-15-Bilag_C.xlsx dname="Bilag_C" icon="file-earmark-text" label="Bilag C" type="button" class="btn btn-link">}}

<!-- jeg har snakket med Lars, og han siger jeg gerne må lægge udtræksbeskrivelserne op.  -->

## Population

The DD2 data are uploaded to SDS, and they check the validity of the CPR-numbers before encrypting them. The data set `DS_EXT_DD2_POP` includes all individuals with a valid CPR-number. Individuals with a non-valid CPR-number are still included in the uploaded data, e.g. in `DS_EXT_DD2CORE`, but they will have a missing encrypted CPR-number (`CPR_ENCRYPTED`) and can thus not be linked across data sources. Previously (when we had local data), we would notify DD2 (Odense) about non-valid CPR-numbers, but this is no longer possible as we are not allowed to identify the individuals based on individual-level data on the servers.

The data files uploaded by us have the prefix `DS_EXT_`. Data are available in 2 versions; the initial upload version (without suffix) and the updated versions (with suffix \_230601, \_231026, etc., corresponding to the date of the update on SDS). The registry data (views) will always be based on the newest population, i.e., individuals in the newest version of `DS_EXT_DD2_POP`. <!-- We are planning to make a new structure where the library will only contain the current version of out own data plus the registry data based on the current version. Previous versions of our own data will be stored in a separate file and will be given a suffix when it is moved. -->

## Rawdata available on SDS

Data on SDS are based on data views, i.e., we have access to data updated (almost) on a day-to-day basis. The update file (SAS `IN06014.OpdateringsOversigt`) contains the time of the current update for each data set in the library. The metadata file (SAS `metadata.metadata_allcolumns`) contains information about variables in the data. For research projects, in order to be able to reproduce results, remember to save a copy of the research data in a suitable project folder on SDS.

<!-- Teams-besked fra Uffe (redigeret) -->

::: callout-note
Using SAS, if you extract data from views you will likely save a lot of time by writing code that is proper sql, rather than using SAS-specific syntax
:::

```{r, eval=FALSE}
Example:
1)

proc sql;
  create table x as
  select *
  from data.lab_lab_dm_forsker(where = (analysiscode in: ([list of npucodes])));
quit; * takes ~40 minutes to run

2)
proc sql;
  create table x as
  select *
  from data.lab_lab_dm_forsker
  where analysiscode eqt [npucode1] or ... or analysiscode eqt [npucodeN];
quit; * takes ~40 minutes to run


3)
proc sql;
  create table x as
  select *
  from data.lab_lab_dm_forsker
  where analysiscode like [npucode1%] or ... or analysiscode like [npucodeN%];
quit; * takes ~10-20 seconds to run
```

Further documentation on the main data sources can be found here:

-   CPR-registret (CPR): [documentation](https://sundhedsdatastyrelsen.dk/da/registre-og-services/om-de-nationale-sundhedsregistre/personoplysninger-og-sundhedsfaglig-beskaeftigelse/cpr-registeret)\
    References: @Schmidt_EurJEpi_2014

-   Landspatientregistret (LPR2 and LPR3): [documentation](https://sundhedsdatastyrelsen.dk/da/registre-og-services/om-de-nationale-sundhedsregistre/sygdomme-laegemidler-og-behandlinger/landspatientregisteret), [LPR3](https://sundhedsdatastyrelsen.dk/da/forskerservice/om-forskerservice/nyheder_forskerservice/helbredsforloeb_lpr3f070422), [LPR3 vejledning](https://sundhedsdatastyrelsen.dk/-/media/sds/filer/Forskerservice/Vejledning%20til%20LPR3_F)\
    References: @Schmidt_ClinEpi_2015

-   Lægemiddelstatistikregistret (LRS/LMS): [documentation](https://sundhedsdatastyrelsen.dk/da/registre-og-services/om-de-nationale-sundhedsregistre/sygdomme-laegemidler-og-behandlinger/laegemiddelstatistikregisteret)\
    References: @Kildemoes_ScanJPubHeal_2011, @Johannesdottir_ClinEpi_2012, @Pottegard_IntJEpi_2017, @Ehrenstein_ClinEpi_2010

-   Laboratoriedatabasen (LAB-F/RLRR): [documentation](https://sundhedsdatastyrelsen.dk/da/registre-og-services/om-de-nationale-sundhedsregistre/doedsaarsager-og-biologisk-materiale/laboratoriedatabasen)\
    References: @Grann_ClinEpi_2011, @Arendt_ClinEpi_2020

### Access to data

All DD2-researchers with access to FSEID-00006014 can (in principle) work with all the data sets. As these data sets are considered rawdata, they are cannot be edited/changed/moved/renamed/etc. To access data, please do the following:

-   **SAS**: The data are already available in the libraries `in06014` and `metadata`

-   **STATA**: Run the (relevant parts of the) DO file located at `F:\Projekter\FSEID00006014\DB Connections FSED00006014.do`

-   **R**: Run the (relevant parts of the) R file located at `F:\Projekter\FSEID00006014\DB Connections FSED00006014.R`

In each research project, it is the individual researchers' responsibility to ensure data usage is allowed.

## Data uploads

The first data were uploaded in 2022 when the server access was initially established. Since then, the data have been updated multiple times.

| Short description | Detailed description | Date | Affected data sets |
|------------------|--------------------|:-----------------|-----------------:|
| Original upload | Upload of data sets for the initial server access | Summer 2022 | DD2CORE, DD2_POP, BIOBANK, DDDA, FOEDSELSDATA, IDNC, IL6_TNF |
| General update | Population update and inclusion of data source FODSTATUS. The biobank was updated with additional measurements of CRP, c-peptide, glucose, and HOMA (from April 2022), and additional "pladebiomarkører" were added to IL6_TNF. DDDA data were updated (June 2022) before the registry closed. IDNC was trimmed to the current population. | June 2023 (\_230621) | DD2CORE, DD2_POP, BIOBANK, DDDA, FOEDSELSDATA, IDNC, IL6_TNF, FODSTATUS |
| Upload of biobank data | C-peptide and glucose (and therefore also HOMA) were changed, and the remaining "pladebiomarkører" were added to IL6_TNF, which is now complete | Fall 2023 (\_231026) | BIOBANK, IL6_TNF |
| Upload of biobank data (genetics) | Genetic variables (polygenic risk scores) were added to IL6_TNF (long format). All new variables are labelled "Gen1" | April 2024 (\_240429) | IL6_TNF |
| Upload of biobank data (genetics) and DICTA variable | Additional genetic variables were added to IL6_TNF. In DD2CORE the DICTA variable was added. | July 2024 (\_240711) | DD2CORE, IL6_TNF |
| Population update and upload of genetics | The population (and registries) was updated (November 2023) and additional genetic variables were included. We made the SDS update in the same round where the DST data were updated (genindstilling via DDV), and decided to rename IL6_TNF to BIOMARK including only the "pladebiomarkører", and including the genetic variables in a separate data set called GENETIK. The data set INFODATA including e.g., DICTA was also included. | December 2024 (upload not available as we are waiting for SDS updates) | DD2CORE, DD2_POP, BIOMARK, GENETIK, INFODATA |

NB: we try to distinguish between "update" and "upload". An "update" means that the population, and therefore also the registry data, has changed, and that the entire DD2 cohort should be seen as a new version. By "upload" we mean additional data uploaded to the current population. This could for example be adding analyses from the biobank or adding a new data source, i.e., something that doesn't affect the population itself. The plan is to make one annual update (November/end of the year) and two to three additional uploads during per year.

<!-- ## Simple versions of data (macro) -->

<!-- mulig gennemgang af simple udtræk + macroer -->
